import json
from collections import deque, Counter, defaultdict
from functools import cache
import math
from typing import Iterable, TypedDict, NotRequired, Literal

from matplotlib.style.core import available
from sage.combinat.partition import Partitions_length_and_parts_constrained
from sage.combinat.posets.poset_examples import posets

from sage.graphs.digraph import DiGraph
from sage.sets.disjoint_set import DisjointSet_of_hashables as DisjointSet

from partial_graph_map import PartialGraphMap
from utils import (
    with_attributes,
    from_rle,
    run_positions,
    dedupe_adjacent,
    first_truthy,
    first,
    stack_graph,
    transpose_list,
    unnest,
)

type DegreeSeq = tuple[tuple[int, int], ...]
type DegreeDict = dict[int, int]


class StackInfo(TypedDict, total=False):
    stacks: list[list[int]]
    images: list[tuple[int, tuple[int]]]
    indices: NotRequired[dict[int, int]]
    graph: NotRequired[DiGraph]


def get_candidates(loc):
    with open(loc, "r") as file:
        return {
            cc: {
                int(nverts): [
                    with_attributes(
                        DiGraph(
                            edge_list,
                            format="vertices_and_edges",
                            multiedges=True,
                            loops=True,
                            immutable=True,
                        ),
                    )
                    for edge_list in edge_lists
                ]
                for nverts, edge_lists in data.items()
            }
            for cc, data in json.load(file).items()
        }


def get_candidates_flat(loc):
    with open(loc, "r") as file:
        return list(
            with_attributes(
                DiGraph(
                    edge_list,
                    format="vertices_and_edges",
                    multiedges=True,
                    loops=True,
                    immutable=True,
                ),
                candidate_nested_index=i,
                curve_complex=cc,
            )
            for cc, data in json.load(file).items()
            for nverts, edge_lists in data.items()
            for i, edge_list in enumerate(edge_lists)
        )


def filter_candidate_transition_graphs(candidates, rank, canonical=True):
    return list(
        with_attributes(candidate, candidate_maps=candidate_maps, candidate_index=i)
        for i, candidate in enumerate(candidates)
        if (candidate_maps := candiate_train_track_maps(candidate, rank, canonical))
    )


def candidate_summary(g: DiGraph):
    return {
        "vertices": list(g.vertices()),
        "edges": list(g.edges()),
        "lambda": float(max(g.adjacency_matrix().eigenvalues())),
        "stacks": stack_info(g)[0],
        "candidate_maps": {
            str(k): [str(map) for map in l] for k, l in g.candidate_maps.items()
        },
    }


def extract_position(candidate: DiGraph):
    """Returns the index of a candidate digraph suitable for use with Mathematica's Extract"""
    return f'{{Key["{candidate.curve_complex}"], Key[{len(candidate)}], {
        candidate.candidate_list_index + 1
    }}}'


def stack_info(tg: DiGraph, canonical=False, indices=False, graph=False) -> StackInfo:
    r"""
    List the stacks and images of final edges for a transition digraph

    Given a digraph ``tg`` representing the transition matrix of a graph map
    :math:`f : G \to G`, a stack is an equivalence class of edges in :math:`G` (vertices in ``tg``)
    generated by the relation :math:`e \sim f(e)` if :math:`e` is neither mixing nor surplus
    (equivalently, if `e` has out-degree 1 as a vertex of ``tg``, and this neighbor has in-degree 1).
    Stacks are returned as lists in mapping order, ``[e, f(e), f(f(e)), ...]``.

    .. WARNING::

    Algorithm assumes but does not check that ``tg`` is strongly connected.

    INPUT:

    - ``tg`` -- DiGraph, the strongly connected transition digraph of an irreducible graph map ``f``.

    OUTPUT: a tuple of

    - list of stacks partitioning the vertices of ``tg``
    - list of pairs ``(v, out_neighbors)``, one for each vertex of
      ``tg`` with outdegree > 1. Vertices in ``out_neighbors`` are listed with multiplicity.

    """

    stacks = list[list]()
    stack_index = dict[int, int]()
    images = list[tuple[int, tuple[int]]]()
    queue = deque[int]()

    def get_index(v, start=None):
        if v not in stack_index:
            if start is None:
                start = v
            ws = tg.neighbors_out(v)
            if tg.out_degree(v) == 1 and tg.in_degree(ws[0]) == 1 and ws[0] != start:
                # really v should be inserted in front, but that's expensive
                # instead we append and then reverse all stacks later
                stacks[stack_index.setdefault(v, get_index(ws[0], start))].append(v)
            else:
                stack_index[v] = len(stacks)
                stacks.append([v])
                images.append((v, tuple(w for w in ws for _ in tg.edge_label(v, w))))
                queue.extend(w for w in ws if w not in stack_index)

        return stack_index[v]

    if len(tg) > 0:
        queue.append(first(tg))

    while queue:
        get_index(queue.popleft())

    for stack in stacks:
        stack.reverse()

    result = StackInfo(stacks=stacks, images=images)
    if indices:
        result["indices"] = stack_index

    if not (canonical or graph):
        return result

    sg = stack_graph(stacks, images, stack_index, canonicalize=canonical)

    if graph:
        result["graph"] = sg

    return result


def lsbi(n):
    """Return index of lowest set bit, or -1 if `n` is 0"""
    return (n & -n).bit_length() - 1


def changeable_run_positions(A: Iterable, preserve):
    if not preserve:
        yield from run_positions(A)
        return

    preserve = {x: True for x in preserve}
    iterator = iter(A)
    start = i = 0
    try:
        x = next(iterator)
    except StopIteration:
        return

    for y in iterator:
        i += 1
        if x != y:
            if x in preserve and preserve[x]:
                preserve[x] = False
            else:
                yield start, i
            start = i
        x = y

    if not (x in preserve and preserve[x]):
        yield start, i + 1


def valid_paths(
    edges: Iterable[int],
    signed=True,
    /,
    positive=None,
    forward: dict[int, int] | bool | None = None,
):
    r"""
    Generate all nondegenerate paths over a collection of edges

    A nondegenerate path is a sequence of edges with no subsequences of the form :math:`e, e^{-1}`.
    Edges are encoded as nonzero integers with sign indicating orientation:
    `-n` is treated as `n` traversed in reverse.
    A collection of edges which should initially be traversed positively.
    For every edge `e` in ``preserve``, we only generate paths which the first occurence of `e` has positive sign.

    Input:

    - ``edges`` -- collection of positive integers. Elements need not be distinct.

    - ``positive`` -- collection of positive integers representing the edges that should
      have a positive orientation the first time they appear in a generated path

    Output: a generator yielding paths over ``edges`` as tuples of length ``len(edges)``.
    """
    A = list(abs(e) for e in edges)
    if not A:
        return
    A.sort()
    n = len(A)

    if not forward:
        is_acceptable = lambda: True
    elif isinstance(forward, dict):
        is_acceptable = lambda: (
            first_truthy(forward[A[i]] - forward[A[n - i - 1]] for i in range(n // 2))
            <= 0
        )
    else:
        is_acceptable = lambda: (
            first_truthy(A[i] - A[n - i - 1] for i in range(n // 2)) <= 0
        )

    while True:
        # A holds a permutation of the positive edges
        if (
            is_acceptable()
        ):  # if the permutation is not a reversal of one that came before it
            # yield all valid combinations of signs
            # we change signs in-place and end up back where we started (all entries positive)
            if signed and (
                runs := list(changeable_run_positions(A, positive))
            ):  # runs of identical edges must have the same sign
                for i in range(1 << len(runs)):
                    yield tuple(A)
                    # gray[i] ^ gray[i-1] == 1 << lowest_set_bit_index(i)
                    for j in range(*runs[lsbi(i)]):
                        A[j] = -A[j]
            else:
                yield tuple(A)

        # All entries of A are once again positive. generate the next permutation
        # https://en.wikipedia.org/wiki/Permutation#Generation_in_lexicographic_order
        for i in range(n - 2, -1, -1):
            if A[i] < A[i + 1]:
                break
        else:
            return

        for j in range(n - 1, i, -1):
            if A[i] < A[j]:
                break

        A[i], A[j] = A[j], A[i]
        A[i + 1 :] = A[: i - n : -1]  # A[i + 1:][::-1]


def degree_sequence(vert_partition: DisjointSet) -> DegreeSeq:
    """Get the degree sequence associated with a partition of edge germs."""
    degs = {}
    for subset in vert_partition:
        n = len(subset)
        if n not in degs:
            degs[n] = 1
        else:
            degs[n] += 1

    return tuple(
        sorted(degs.items(), reverse=True)
    )  # (tuple((k, degs[k]) for k in sorted(degs, reverse=True)))


def max_trivalent(degs: dict[int, int]):
    r"""
    Return the maximum number of valence-3 verts among all graphs that can be
    obtained from a graph with the given degree sequence by identifying vertices.
    """
    ones = degs.get(1, 0)
    m = min(degs.get(2, 0), ones)
    return degs.get(3, 0) + m + (ones - m) // 3


@cache
def _integer_partitions_poset(n: int):
    """Return a cached instance of posets.IntegerPartitions(n)"""
    return posets.IntegerPartitions(n)


@cache
def _is_admissible_degree_sequence(degs: DegreeSeq, rank: int) -> bool:
    r"""
    Check whether a degree sequence is admissible in the given rank.

    We say a degree sequence is admissible in rank `r` if it can be
    realized by a graph `G` whose edge germ partition is admissible in rank `r`.
    Equivalently, if the vertices of `G` can be identified to produce
    a connected graph of rank `r` with no valence :math:`\le 2` vertices.

    Inputs:

    - ``degs`` -- degree sequence, represented as a run-length encoded tuple of
      integer pairs :math:`(d_k, n_k), \dots, (d_1, n_1)`, where :math:`d_k > \dotsc > d_1`.

    - ``rank`` -- positive integer

    Outputs: ``True`` if ``degs`` is admissible in the given rank
    """
    N, n_verts, n_edges = cell_counts(degs, rank)

    # first run a simple check based on number of trivalent vertices
    min_trivalent = max(
        0, n_verts - (N - 3 * n_verts)
    )  # min number of deg-3 verts req'd for this graph to have no valence <= 2 verts
    if max_trivalent(dict(degs)) < min_trivalent:
        return False

    # no more quick checks, we need to verify
    deg_part = tuple(from_rle(degs))
    poset = _integer_partitions_poset(N)

    # equivalent to Partitions(N, length=n_verts, min_part=3)
    for part in Partitions_length_and_parts_constrained(N, n_verts, n_verts, 3, N):
        if poset.is_gequal(deg_part, tuple(part)):  # deg_part is a refinement of part
            return True
    else:
        return False


def is_admissible_partition(germs: DisjointSet, rank: int) -> bool:
    r"""
    Check whether a partition of edge germs is admissible in the given rank.

    We say a disjoint union of edge germs `P` is admissible in rank `r`
    if there exists a connected graph `G` of rank `r` such that:

    - `G` has no vertices of degree :math:`\le 2`, and
    - `P` is a refinement of the partition on edge germs given by the vertices of `G`.

    Inputs:

    - ``germs`` -- disjoint set of edge germs

    - ``rank`` -- positive integer, the rank of `G`

    Outputs: ``True`` if ``germs`` is admissible in the given rank.
    """
    return _is_admissible_degree_sequence(degree_sequence(germs), rank)


def depth_first_neighbors(g: DiGraph, start):
    neighbors = {v: set() for v in g}
    for u, v in g.depth_first_search(start, edges=True):
        neighbors[u].add(v)
    return neighbors


def candiate_train_track_maps(tg: DiGraph, rank: int, canonical=True):
    """
    Get all candidates for train-track maps with a given transition digraph and domain rank

    Inputs:

    - ``tg`` -- digraph with positive integer vertices. Should be strongly connected.
    - ``rank`` -- positive integer

    Outputs: a list of pairs ``(f, pf)``

    - ``f`` -- ``PartialGraphMap`` with transition digraph ``tg``. Returned maps are
      guaranteed to be train-track and complete (no edge images left unspecified).
    - ``pf`` -- disjoint set of integers representing the partition induced by ``f`` on edge germs of its domain.

    Returns ``[]`` if no such maps exist.
    """
    n_edges = len(tg)
    n_verts = n_edges - rank + 1

    info = stack_info(tg, canonical=canonical, indices=canonical, graph=canonical)
    stacks = info["stacks"]
    edge_mappings = info["images"]
    candidate_maps = list[tuple[PartialGraphMap, DisjointSet]]()

    if canonical:
        s = info["indices"]
        sg = info["graph"]
        o = depth_first_neighbors(sg, 0)
        positive = {
            e: tuple(img_e for img_e in dedupe_adjacent(img) if s[img_e] in o[s[e]])
            for e, img in edge_mappings
        }
        forward = {
            first_truthy(
                e
                for e, img in edge_mappings
                if len(img) > 1 and s[img[0]] != s[img[-1]]
            ): s
        }
    else:
        positive = {}
        forward = {}

    def go(f: PartialGraphMap, germs: DisjointSet, remaining: list[tuple]):
        if len(remaining) == 0:
            if is_admissible_partition(germs, rank):
                candidate_maps.append((f, germs))
            return

        (e, image_edges), *remaining = remaining

        for fe in valid_paths(
            image_edges,
            positive=positive.get(e, None),
            forward=forward.get(e, None),
        ):
            new_f = f.new_edge_mapping(e, fe)
            try:
                new_verts = new_f.identify_vertices(
                    germs,
                    assert_train_track=True,
                    min_subsets=n_verts - 1,
                )
                if new_verts.number_of_subsets() >= n_verts:
                    go(new_f, new_verts, remaining)
            except AssertionError:  # exception raised if new_f is not train-track
                continue

    go(
        PartialGraphMap.from_stacks(stacks),
        DisjointSet(i for i in range(-n_edges, n_edges + 1) if i),
        edge_mappings,
    )

    return candidate_maps


def cell_counts(degs: DegreeSeq | DegreeDict, rank: int):
    N = sum(
        d * n for d, n in (degs.items() if isinstance(degs, dict) else degs)
    )  # sum of vertex degrees

    # number of verts and edges in a conn. graph with the given rank and degree seq
    if N % 2 == 0:
        n_edges = N // 2
    else:  # sequence is not graphical
        raise ValueError("Sum of vertex degrees must be even")
    n_verts = n_edges - rank + 1

    return N, n_verts, n_edges


def train_track_domains(f: PartialGraphMap, germs: DisjointSet, rank):
    degs = degree_sequence(germs)
    N, n_verts, n_edges = cell_counts(degs, rank)

    # no more quick checks, we need to verify
    deg_partition = tuple(from_rle(degs))

    poset = _integer_partitions_poset(N)

    # equivalent to Partitions(N, length=n_verts, min_part=3)
    for part in Partitions_length_and_parts_constrained(N, n_verts, n_verts, 3, N):
        if poset.is_gequal(
            deg_partition, tuple(part)
        ):  # deg_part is a refinement of part
            return True
    else:
        return False


def train_track_maps(tg: DiGraph, rank: int):
    n_edges = len(tg)
    N = 2 * n_edges
    n_verts = n_edges - rank + 1
    if hasattr(tg, "candidate_maps"):
        candidate_maps = tg.refinement
    else:
        candidate_maps = candiate_train_track_maps(tg, rank)
        tg.candidate_maps = candidate_maps

    for f, germs in candidate_maps:
        degs = degree_sequence(germs)
        deg_part = from_rle(degs)
        poset = _integer_partitions_poset(N)

        # equivalent to Partitions(N, length=n_verts, min_part=3)
        for part in Partitions_length_and_parts_constrained(N, n_verts, n_verts, 3, N):
            if poset.is_gequal(
                deg_part, tuple(part)
            ):  # deg_part is a refinement of part
                return True


# def mergings(d: dict[int, int], target_len):
#     print(f"merging {d}")
#     l = sum(d.values())
#     print(f"sum = {l}")
#     if l == target_len:
#         yield d
#         return
#     elif l > target_len:
#         keez = list(d.keys())
#         keez.sort(reverse=True)
#         print(keez)
#         for i in range(len(keez)):
#             ki = keez[i]
#             for j in range(i + 1):
#                 kj = keez[j]
#                 print(f"({i}, {j}) -> {ki}, {kj}")
#                 if i != j or d[ki] > 1:
#                     print("gothere")
#                     nd = dict(d)
#                     nd[ki] -= 1
#                     nd[kj] -= 1
#                     if ki + kj in nd:
#                         nd[ki + kj] += 1
#                     else:
#                         nd[ki + kj] = 1
#
#                     print("gothere")
#                     if nd[ki] == 0:
#                         del nd[ki]
#                     if ki != kj and nd[kj] == 0:
#                         del nd[kj]
#
#                     print("gothere")
#                     yield from mergings(nd, target_len)


def degree_tuple(dict: DegreeDict | Counter[int]) -> DegreeSeq:
    return tuple(sorted(dict.items(), reverse=True))


def int_tuple_cmp(a: int | tuple[int, ...], b: int | tuple[int, ...]) -> int:
    if isinstance(a, tuple):
        if isinstance(b, tuple):
            if a == b:
                return 0
            elif a < b:
                return -1
            else:
                return 1
        else:
            return 1
    else:
        if isinstance(b, tuple):
            return -1
        else:
            return a - b


def structural_sort(list: list):
    pass


# def dict_add_sorted(ks, vs, new_k):
#     new_dict = {}
#     added = False
#     for i, k in enumerate(ks):
#         new_dict[k] = vs[i]
#         if not added:
#             if k > new_k


def merge_results(degs, merges):
    # subsets = {d: Counter({d: m}) for d, m in degs}
    merges = list(unnest(merges))
    merges.reverse()
    return merges


type NestedTuple[T] = None | tuple[T, NestedTuple[T]]


def max_threes(degs: Counter[int], moves: int, verbose=False):
    ones = degs[1]
    pairs = min(degs[2], ones, moves)
    extra_ones = (ones - pairs)
    extra_moves = (moves - pairs)
    surplus = min(extra_ones // 3, extra_moves // 2)
    max_3s = degs[3] + pairs + surplus

    leftover_moves = extra_moves - 2 * surplus
    if verbose:
        print(f'{degs[3]} threes already present')
        print(f'{ones} ones, {degs[2]} twos, {moves} moves -> {pairs} pairs')
        print(f'{extra_ones} ({extra_ones // 3}) extra ones , {extra_moves} ({extra_moves // 2}) extra moves  -> {surplus} extra threes')
        print(f'{max_3s} threes with {leftover_moves} moves left over')
    # available_ones = extra_ones // 3


    # if moves <= pairs:
    #     pairs = moves
    #     actual_ones = 0
    # else:
    # available_ones = (ones - pairs) // 3
    # actual_ones = min(available_ones, (moves - pairs) // 2)

    return degs[3] + pairs + surplus


def min_merges_until_acceptable(degs: Counter[int]):
    ones = degs[1]
    twos = degs[2]
    pairs = min(ones, twos)

    return (
        pairs
        + (twos - pairs + 1) // 2
        + ((ones - pairs + 1) // 2 + ((ones - pairs) // 2 + 1) // 2)
    )


def union_generator(
    degs: DegreeDict | Counter[int], n_merges, n_threes, report_merges=False
):
    if not isinstance(degs, Counter):
        degs = Counter(degs)

    # N, n_verts, n_edges = cell_counts(degs, rank)
    # n_merges = n_verts - degs.total()

    def go(counts: Counter[int], n: int, merges: NestedTuple[tuple[int, int]] = None):
        debug_str = f"{dict(counts)}, {(merges[0] if merges else (0, 0))}, {n}"

        if min_merges_until_acceptable(counts) > n:
            print(debug_str + f": can't get rid of all deg <= 2 verts")
            return
        max_3s = max_threes(counts, n)
        debug_str += f"; [{max_3s}]"
        if max_3s < n_threes:
            print(debug_str + f": can't make {n_threes} threes in {n} moves")
            return
        if n <= 0:
            print(f"\tyielding " + debug_str)
            if report_merges:
                yield (degree_tuple(counts), merge_results(degs, merges))
            else:
                yield degree_tuple(counts)
            return
        print(debug_str)
        degrees = sorted(counts)
        prev_di, prev_dj = merges[0] if merges is not None else (0, 0)
        for i, di in enumerate(degrees):
            if di < prev_di:
                continue
            counts[di] -= 1
            for j, dj in enumerate(degrees):
                if j > i or i == j and counts[di] == 0:
                    break
                elif dj < prev_dj:
                    continue
                counts[dj] -= 1
                yield from go(
                    counts + Counter((di + dj,)),
                    n - 1,
                    ((di, dj), merges if report_merges else None),
                )
                counts[dj] += 1
            counts[di] += 1

    return go(Counter(degs), n_merges)


def mergings(degs: DegreeDict | Counter[int], n_merges, n_threes):
    found = {}
    for deg_seq, merges in union_generator(
        degs, n_merges, n_threes, report_merges=True
    ):
        if deg_seq in found:
            found[deg_seq].append(merges)
        else:
            found[deg_seq] = [merges]
    return found


def germ_domain(germs: DisjointSet):
    d = germs.element_to_root_dict()
    return DiGraph([(d[e], d[-e], e) for e in d if e > 0], multiedges=True, loops=True)


def vec_mergings(d: dict[int, int], target_len):
    v0 = [0] * sum(k * v for k, v in d.items())
    for k, v in d.items():
        v0[k - 1] = v

    def gen_mergings(vec: list, n, hist):
        print(f"vec = {vec}")
        vec = list(vec)
        if n == 0:
            ds = {}
            for i in range(len(vec)):
                if vec[i] == 0:
                    continue
                ds[i + 1] = vec[i]

            yield vec, hist
            return

        for i in range(len(vec)):
            if vec[i] == 0:
                continue

            vec[i] -= 1
            for j in range(i + 1):
                if vec[j] == 0:
                    continue

                vec[j] -= 1
                print(f'merging {i} and {j} on {vec}')
                vec[i + j + 1] += 1
                print(f'result {vec}')
                yield from gen_mergings(vec, n - 1, hist + [(i + 1, j + 1)])

                vec[j] += 1
                vec[i + j + 1] -= 1
            vec[i] += 1

    print(v0)

    return gen_mergings(v0, sum(d.values()) - target_len, [])


if __name__ == "__main__":
    f5candidates = get_candidates_flat("../data/f5candidates.json")
    # tg2 = f5candidates["3A1"][11][22]
    print(stack_info(f5candidates[12]))
