from collections import deque, Counter
from functools import cache
from typing import (
    Iterable,
    TypedDict,
    NotRequired,
    Generator,
    Any,
    Sequence,
    Callable,
)

from sage.graphs.digraph import DiGraph
from sage.groups.perm_gps.permgroup import PermutationGroup
from sage.sets.disjoint_set import DisjointSet_of_hashables as DisjointSet

from partial_graph_map import PartialGraphMap
from utils import (
    rle,
    with_attributes,
    run_positions,
    dedupe_adjacent,
    first_truthy,
    first,
    stack_graph,
    unnest,
    nneg,
    shortlex,
    lsbi,
    deep_tuple,
    NestedTuple,
)

type DegreeSeq = tuple[tuple[int, int], ...]
type DegreeDict = dict[int, int]  # includes Counter[int]
type DegreePartition = PartitionTuple[int]
type Degrees = DegreeDict | DegreeSeq

type PartitionTuple[T] = tuple[tuple[T, ...], ...]
type Merges = NestedTuple[tuple[int, int]]


class StackInfo(TypedDict, total=False):
    stacks: list[list[int]]
    images: list[tuple[int, tuple[int]]]
    indices: NotRequired[dict[int, int]]
    graph: NotRequired[DiGraph]


def stack_info(tg: DiGraph, canonical=False, indices=False, graph=False) -> StackInfo:
    r"""
    List the stacks and images of final edges for a transition digraph

    Given a digraph ``tg`` representing the transition matrix of a graph map
    :math:`f : G \to G`, a stack is an equivalence class of edges in :math:`G` (vertices in ``tg``)
    generated by the relation :math:`e \sim f(e)` if :math:`e` is neither mixing nor surplus
    (equivalently, if `e` has out-degree 1 as a vertex of ``tg``, and this neighbor has in-degree 1).
    Stacks are returned as lists in mapping order, ``[e, f(e), f(f(e)), ...]``.

    .. WARNING::

    Algorithm assumes but does not check that ``tg`` is strongly connected.

    INPUT:

    - ``tg`` -- DiGraph, the strongly connected transition digraph of an irreducible graph map ``f``.

    OUTPUT: a tuple of

    - list of stacks partitioning the vertices of ``tg``
    - list of pairs ``(v, out_neighbors)``, one for each vertex of
      ``tg`` with outdegree > 1. Vertices in ``out_neighbors`` are listed with multiplicity.

    """

    stacks = list[list]()
    stack_index = dict[int, int]()
    images = list[tuple[int, tuple[int]]]()
    queue = deque[int]()

    def get_index(v, start=None):
        if v not in stack_index:
            if start is None:
                start = v
            ws = tg.neighbors_out(v)
            if tg.out_degree(v) == 1 and tg.in_degree(ws[0]) == 1 and ws[0] != start:
                # really v should be inserted in front, but that's expensive
                # instead we append and then reverse all stacks later
                stacks[stack_index.setdefault(v, get_index(ws[0], start))].append(v)
            else:
                stack_index[v] = len(stacks)
                stacks.append([v])
                images.append((v, tuple(w for w in ws for _ in tg.edge_label(v, w))))
                queue.extend(w for w in ws if w not in stack_index)

        return stack_index[v]

    if len(tg) > 0:
        queue.append(first(tg))

    while queue:
        get_index(queue.popleft())

    for stack in stacks:
        stack.reverse()

    result = StackInfo(stacks=stacks, images=images)
    if indices:
        result["indices"] = stack_index

    if not (canonical or graph):
        return result

    sg = stack_graph(stacks, images, stack_index, canonicalize=canonical)

    if graph:
        result["graph"] = sg

    return result


def changeable_run_positions(A: Iterable, preserve):
    preserve = {x: True for x in preserve}
    iterator = iter(A)
    start = i = 0
    try:
        x = next(iterator)
    except StopIteration:
        return

    for y in iterator:
        i += 1
        if x != y:
            if x in preserve and preserve[x]:
                preserve[x] = False
            else:
                yield start, i
            start = i
        x = y

    if not (x in preserve and preserve[x]):
        yield start, i + 1


def valid_paths(
    edges: Iterable[int],
    signed=True,
    /,
    positive=None,
    forward: dict[int, int] | bool | None = None,
):
    r"""
    Generate all nondegenerate paths over a collection of edges

    A nondegenerate path is a sequence of edges with no subsequences of the form :math:`e, e^{-1}`.
    Edges are encoded as nonzero integers with sign indicating orientation:
    `-n` is treated as `n` traversed in reverse.
    A collection of edges which should initially be traversed positively.
    For every edge `e` in ``preserve``, we only generate paths which the first occurence of `e` has positive sign.

    Input:

    - ``edges`` -- collection of positive integers. Elements need not be distinct.

    - ``positive`` -- collection of positive integers representing the edges that should
      have a positive orientation the first time they appear in a generated path

    Output: a generator yielding paths over ``edges`` as tuples of length ``len(edges)``.
    """
    A = [abs(e) for e in edges]
    if not A:
        return
    A.sort()
    n = len(A)

    if not forward:

        def is_acceptable():
            return True

    elif isinstance(forward, dict):

        def is_acceptable():
            return (
                first_truthy(
                    forward[A[i]] - forward[A[n - i - 1]] for i in range(n // 2)
                )
                <= 0
            )

    else:

        def is_acceptable():
            return first_truthy(A[i] - A[n - i - 1] for i in range(n // 2)) <= 0

    while True:
        # A holds a permutation of the positive edges
        if is_acceptable():  # permutation is not a reversal of one that came before it
            # yield all valid combinations of signs
            # we change signs in-place and end up back where we started (all entries positive)
            if signed and (
                runs := (
                    [*changeable_run_positions(A, positive)]
                    if positive is not None
                    else [*run_positions(A)]
                )
            ):  # runs of identical edges must have the same sign
                for i in range(1 << len(runs)):
                    yield (*A,)
                    # gray[i] ^ gray[i-1] == 1 << lowest_set_bit_index(i)
                    for j in range(*runs[lsbi(i)]):
                        A[j] = -A[j]
            else:
                yield (*A,)

        # All entries of A are once again positive. generate the next permutation
        # https://en.wikipedia.org/wiki/Permutation#Generation_in_lexicographic_order
        for i in range(n - 2, -1, -1):
            if A[i] < A[i + 1]:
                break
        else:
            return

        for j in range(n - 1, i, -1):
            if A[i] < A[j]:
                break

        A[i], A[j] = A[j], A[i]
        A[i + 1 :] = A[: i - n : -1]  # A[i + 1:][::-1]


def degrees(partition: DisjointSet | Iterable[Sequence[int]]):
    """Get the vertex degrees associated with a partition of edge germs."""
    return Counter(len(subset) for subset in partition)


def degree_counter(data: DisjointSet | DegreeDict | DegreeSeq) -> Counter[int]:
    match data:
        case Counter():
            return data
        case dict():
            return Counter(data)
        case [(int(_), int(_)), *_]:
            return Counter(dict[int, int](data))
        case [*_]:
            return Counter(data)

    raise ValueError(f"Input {data} was not recognized as a degree sequence")


def degree_tuple_rle(degs: Degrees) -> DegreeSeq:
    """Get a degree sequence as a run length encoded tuple"""
    return (
        *sorted(
            degs.items() if isinstance(degs, dict) else degs,
            reverse=True,
        ),
    )


# def degree_sequence(degs: )


# def max_trivalent(degs: dict[int, int]):
#     r"""
#     Return the maximum number of valence-3 verts among all graphs that can be
#     obtained from a graph with the given degree sequence by identifying vertices.
#     """
#     ones = degs.get(1, 0)
#     m = min(degs.get(2, 0), ones)
#     return degs.get(3, 0) + m + (ones - m) // 3


@cache
def _is_admissible_degree_sequence(degs: DegreeSeq, rank: int) -> bool:
    r"""
    Check whether a degree sequence is admissible in the given rank.

    We say a degree sequence is admissible in rank `r` if it can be
    realized by a graph `G` whose edge germ partition is admissible in rank `r`.
    Equivalently, if the vertices of `G` can be identified to produce
    a connected graph of rank `r` with no valence :math:`\le 2` vertices.

    Inputs:

    - ``degs`` -- degree sequence, represented as a run-length encoded tuple of
      integer pairs :math:`(d_k, n_k), \dots, (d_1, n_1)`, where :math:`d_k > \dotsc > d_1`.

    - ``rank`` -- positive integer

    Outputs: ``True`` if ``degs`` is admissible in the given rank
    """
    n_verts, n_edges = vertex_and_edge_count_in_rank(degs, rank)
    degs = Counter(dict(degs))
    # min number of deg-3 verts req'd for this graph to have no valence <= 2 verts
    return (
        first(
            _tt_deg_seq_quotients(
                degs,
                n_verts,
                min_trivalent_vertices(n_verts, n_edges),
                report_unions=False,
            ),
            None,
        )
        is not None
    )


def is_admissible_partition(germs: DisjointSet, rank: int) -> bool:
    r"""
    Check whether a partition of edge germs is admissible in the given rank.

    We say a disjoint union of edge germs `P` is admissible in rank `r`
    if there exists a connected graph `G` of rank `r` such that:

    - `G` has no vertices of degree :math:`\le 2`, and
    - `P` is a refinement of the partition on edge germs given by the vertices of `G`.

    Inputs:

    - ``germs`` -- disjoint set of edge germs

    - ``rank`` -- positive integer, the rank of `G`

    Outputs: ``True`` if ``germs`` is admissible in the given rank.
    """
    return _is_admissible_degree_sequence(degree_tuple_rle(degrees(germs)), rank)


def depth_first_neighbors(g: DiGraph, start):
    neighbors = {v: set() for v in g}
    for u, v in g.depth_first_search(start, edges=True):
        neighbors[u].add(v)
    return neighbors


def candiate_train_track_maps(
    tg: DiGraph, rank: int, canonical=True
) -> list[tuple[PartialGraphMap, DisjointSet]]:
    """
    Get all candidates for train-track maps with a given transition digraph and domain rank

    Inputs:

    - ``tg`` -- digraph with positive integer vertices. Should be strongly connected.
    - ``rank`` -- positive integer

    Outputs: a list of pairs ``(f, pf)``

    - ``f`` -- ``PartialGraphMap`` with transition digraph ``tg``. Returned maps are
      guaranteed to be train-track and complete (no edge images left unspecified).
    - ``pf`` -- disjoint set of integers representing the partition induced by ``f`` on edge germs of its domain.

    Returns ``[]`` if no such maps exist.
    """
    n_edges = len(tg)
    n_verts = n_edges - rank + 1

    info = stack_info(tg, canonical=canonical, indices=canonical, graph=canonical)
    stacks = info["stacks"]
    edge_mappings = info["images"]

    if canonical:
        s = info["indices"]
        sg = info["graph"]
        o = depth_first_neighbors(sg, 0)
        positive = {
            e: tuple(img_e for img_e in dedupe_adjacent(img) if s[img_e] in o[s[e]])
            for e, img in edge_mappings
        }
        forward = {
            first_truthy(
                e
                for e, img in edge_mappings
                if len(img) > 1 and s[img[0]] != s[img[-1]]
            ): s,
        }
    else:
        positive = {}
        forward = {}

    def go(f: PartialGraphMap, germs: DisjointSet, remaining: list[tuple]):
        if len(remaining) == 0:
            if is_admissible_partition(germs, rank):
                yield f, germs
            return

        (e, image_edges), *remaining = remaining

        for fe in valid_paths(
            image_edges,
            positive=positive.get(e, None),
            forward=forward.get(e, None),
        ):
            new_f = f.new_edge_mapping(e, fe)
            try:
                new_verts = new_f.identify_vertices(
                    germs,
                    assert_train_track=True,
                    min_subsets=n_verts - 1,
                )
                if new_verts.number_of_subsets() >= n_verts:
                    yield from go(new_f, new_verts, remaining)
            except AssertionError:  # exception raised if new_f is not train-track
                continue

    return [
        *go(
            PartialGraphMap.from_stacks(stacks),
            DisjointSet(i for i in range(-n_edges, n_edges + 1) if i),
            edge_mappings,
        )
    ]


def filter_candidate_transition_graphs(candidates, rank, canonical=True):
    return list(
        with_attributes(candidate, candidate_maps=candidate_maps, candidate_index=i)
        for i, candidate in enumerate(candidates)
        if (candidate_maps := [*candiate_train_track_maps(candidate, rank, canonical)])
    )


def edge_count(degs: Degrees):
    """Return the number of edges in a graph with the given degree sequence."""
    N = sum(d * n for d, n in (degs.items() if isinstance(degs, dict) else degs))
    if N % 2 == 0:
        return N // 2
    else:
        raise ValueError("Sum of vertex degrees must be even")


def vertex_and_edge_count_in_rank(degs: Degrees, rank: int):
    """
    Determine the number of vertices and edges in a rank-``rank`` quotient of a graph with degree sequence ``degs``.
    """
    n_edges = edge_count(degs)
    return n_edges - rank + 1, n_edges


def min_trivalent_vertices(n_verts: int, n_edges: int):
    r"""
    Return the min number of degree-3 vertices for a connected graph on
    ``n_verts`` vertices and ``n_edges`` edges with no valence <= 2 vertices
    """
    # equal to n_verts - ((sum of degrees) - 3 * n_verts),
    return nneg(4 * n_verts - 2 * n_edges)


def max_trivalent(degs: Counter[int], n_unions: int):
    """
    Compute the maximum number of trivalent vertices possible after `n` identifications

    INPUT:

    ``degs`` - integer Counter, the degree sequence of a graph

    ``n_unions`` - integer, the number of vertex identifications to consider

    OUTPUT: a nonnegative integer, the maximum number of valence-3 vertices
    among graphs obtained by identifying ``n_unions`` vertices of a
    graph with degree sequence ``degs``.
    """
    ones = degs[1]
    twos = degs[2]
    threes = degs[3]
    # number of 3s that can be obtained from 2 + 1
    from_twos = min(ones, twos, n_unions)
    # number of 3s that can come from 1 + 1 + 1 after doing 2 + 1 as many times as possible
    from_ones = min((ones - from_twos) // 3, (n_unions - from_twos) // 2)
    return nneg(
        (threes + from_twos + from_ones)  # max number of 3s possible
        - nneg(  # minimal number of unions involving a 3
            # once we've made as many 3s as possible, there are...
            (n_unions - from_twos - 2 * from_ones)  # unions remaining
            - nneg(  # unions available that don't involve a 3
                (degs.total() - threes - 2 * from_twos - 3 * from_ones) - 1
            )
        )
    )


def min_unions(degs: Counter[int]):
    """
    Find the minimum number of identifications needed to eliminate all valence <= 2 verts

    INPUT:

    ``degs`` - integer Counter, the degree sequence of a graph

    OUTPUT: a nonnegative integer, the minimum number of vertices that must be identified in
    a graph with degree sequence ``degs`` to produce a graph with min vertex degree >= 3
    """
    ones = degs[1]
    twos = degs[2]
    pairs = min(ones, twos)
    paired_ones, remaining_ones = divmod(ones - pairs, 2)

    return (
        pairs
        + (twos - pairs + 1) // 2
        + paired_ones
        + (paired_ones + remaining_ones + 1) // 2
    )


def _tt_deg_seq_quotients(
    degs: Degrees,
    n_verts: int,
    min_trivalent: int,
    report_unions=False,
    full_search=False,
    verbose=False,
) -> Generator[DegreeSeq | tuple[DegreeSeq, Iterable[tuple[int, int]]], Any, None]:
    degs = degree_counter(degs)
    n_unions = degs.total() - n_verts

    def go(
        counts: Counter[int],
        n: int,
        merges: NestedTuple[tuple[int, int]],
        empty_reason=None,
    ):
        if verbose:
            print(
                f"{str(counts).removeprefix('Counter(').removesuffix(')')}, "
                f"{(merges[0] if merges else (0, 0))}, {n}"
            )

        if (min_merges := min_unions(counts)) > n:
            if verbose:
                print(f"invalid (vertices; {min_merges} > {n})")
            if full_search:
                empty_reason = empty_reason or (
                    dict(counts),
                    n,
                    f"vertices: {min_merges} until acceptable",
                )
            else:
                return
        if min_trivalent > 0 and (max_3s := max_trivalent(counts, n)) < min_trivalent:
            if verbose:
                print(f"invalid (threes; {max_3s} < {min_trivalent})")
            if full_search:
                empty_reason = empty_reason or (dict(counts), n, f"threes: {max_3s}")
            else:
                return
        if n <= 0:
            if full_search:
                if counts[1] or counts[2] or counts[3] < min_trivalent:
                    assert empty_reason is not None, f"{counts} slipped through"
                    return
                else:
                    assert empty_reason is None, f"{counts} skipped b/c {empty_reason}"

            if report_unions:
                yield degree_tuple_rle(counts), reversed((*unnest(merges),))
            else:
                yield degree_tuple_rle(counts)
            return

        degrees = sorted(counts)
        prev_di, prev_dj = merges[0] if merges is not None else (0, 0)
        for i, di in enumerate(degrees):
            if di < prev_di:
                continue
            counts[di] -= 1
            for j, dj in enumerate(degrees):
                if j > i or i == j and counts[di] == 0:
                    break
                elif dj < prev_dj:
                    continue
                counts[dj] -= 1
                yield from go(
                    counts + Counter((di + dj,)),
                    n - 1,
                    ((di, dj), merges if report_unions else None),
                    empty_reason,
                )
                counts[dj] += 1
            counts[di] += 1

    return go(degs, n_unions, None)


def _deg_partitions_from_merging(degs: DegreeDict, merges: Merges):
    """"""
    # print(degs, merges)
    merges = reversed((*unnest(merges),))
    # return list(merges)
    states = [{d: Counter({(d,): m}) for d, m in degs.items()}]
    for di, dj in merges:
        new_states = []
        # print(di, dj)
        # print(states)
        for state in states:
            # print(state)
            for i, subset_i in enumerate(state[di]):
                state[di][subset_i] -= 1
                for j, subset_j in enumerate(state[dj]):
                    if di == dj and (j > i or i == j and state[di][subset_i] == 0):
                        break
                    state[dj][subset_j] -= 1
                    new_state = {
                        n: subsets + Counter()
                        for n, subsets in state.items()
                        if subsets.total() > 0
                    }
                    new_subset = (*sorted(subset_i + subset_j),)
                    if (di + dj) in new_state:
                        new_state[di + dj][new_subset] += 1
                    else:
                        new_state[di + dj] = Counter((new_subset,))
                    new_states.append(new_state)
                    state[dj][subset_j] += 1
                state[di][subset_i] += 1
        states = new_states
    return {
        (*sorted(el for subsets in state.values() for el in subsets.elements()),)
        for state in states
    }


def train_track_degree_partitions(
    degs: Degrees, rank: int
) -> dict[DegreeSeq, set[DegreePartition]]:
    degs = degree_counter(degs)
    n_verts, n_edges = vertex_and_edge_count_in_rank(degs, rank)

    found = {}
    for deg_seq, merges in _tt_deg_seq_quotients(
        degs,
        n_verts,
        min_trivalent_vertices(n_verts, n_edges),
        report_unions=True,
    ):
        if deg_seq in found:
            found[deg_seq].update(_deg_partitions_from_merging(degs, merges))
        else:
            found[deg_seq] = _deg_partitions_from_merging(degs, merges)

    return found


def train_track_partitions(
    germs: DisjointSet,
    rank: int,
):
    # degs = Counter(dict(sorted(degs.items())))
    subsets = sorted(germs, key=shortlex)
    degs = degrees(subsets)
    degree_partitions = train_track_degree_partitions(degs, rank)
    # result = dict.fromkeys(degree_partitions)
    result: dict[DegreeSeq, list[DegreePartition]] = {
        deg_seq: [] for deg_seq in degree_partitions
    }
    for deg_seq, deg_parts in degree_partitions.items():
        for deg_part in deg_parts:
            part_idxs, overgroup, subgroup = degree_partition_structure(degs, deg_part)
            # print("degree_seq:", deg_seq)
            # print("partition:    ", deg_part)
            # print("partition idx:", part_idxs)
            # print(subgroup)
            for rep, _ in overgroup.gap().DoubleCosetRepsAndSizes(subgroup, subgroup):
                perm = rep.sage(overgroup)
                # edge germ partition
                partition = deep_tuple(
                    sorted(
                        (
                            sorted(el for i in subset for el in subsets[perm(i) - 1])
                            for subset in part_idxs
                        ),
                        key=shortlex,
                    )
                )
                if is_connected_domain(partition):
                    result[deg_seq].append(partition)
    return result


def degree_partition_structure(degs: Counter[int], deg_part: DegreePartition):
    # indices = {d: (i := i + n) - n for d, n in sorted(degs.items())}
    dom = [*range(1, degs.total() + 1)]
    overgp_gens = []
    i = 1
    indices = dict.fromkeys(degs, 0)
    for d, n in sorted(degs.items()):
        indices[d] = i
        if n > 1:  # add an n-cycle
            overgp_gens.append([(*range(i, i + n),)])
        if n > 2:  # add a transposition
            overgp_gens.append([(i, i + 1)])
        i += n

    subset_idxs = []
    subgp_gens = []
    prev_subset = None
    for subset in deg_part:
        indexed_subset = []
        for d, n in rle(subset):
            j = indices[d]
            indexed_subset.extend(range(j, j + n))
            if n > 1:  # add an n-cycle
                subgp_gens.append([(*range(j, j + n),)])
            if n > 2:  # add a transposition
                subgp_gens.append([(j, j + 1)])
            if subset == prev_subset:  # add a transposition between subsets
                subgp_gens.append([(j - n, j)])
            indices[d] += n
        subset_idxs.append((*indexed_subset,))
        prev_subset = subset

    # print("overgroup gens:", overgp_gens)
    # print("subgroup gens:", subgp_gens)
    overgroup = PermutationGroup(overgp_gens, domain=dom)
    return (
        (*subset_idxs,),
        overgroup,
        overgroup.subgroup(subgp_gens, domain=dom),
    )


def root_to_elements_dict(
    partition: DisjointSet | Iterable[Sequence[int]],
) -> dict[int, Sequence[int]]:
    if isinstance(partition, DisjointSet):
        return partition.root_to_elements_dict()
    else:
        return {subset[0]: subset for subset in partition}


def element_to_root_dict(
    partition: DisjointSet | Iterable[Sequence[int]],
) -> dict[int, int]:
    if isinstance(partition, DisjointSet):
        return partition.element_to_root_dict()
    else:
        return {x: seq[0] for seq in partition for x in seq}


def is_connected_domain(partition: DisjointSet | Iterable[Sequence[int]]):
    d = root_to_elements_dict(partition)
    lookup: Callable[[int], int] = (
        partition.find
        if isinstance(partition, DisjointSet)
        else {x: r for r, s in d.items() for x in s}.__getitem__
    )

    if not d:
        return True
    queue = deque[int](d.popitem()[1])
    while queue:
        if not d:
            return True
        v = lookup(-queue.popleft())
        if v in d:
            queue.extend(d.pop(v))
    else:
        return not partition


def domain_graph(vp: DisjointSet | Iterable[Sequence[int]], canonical=True):
    d = element_to_root_dict(vp)
    dom = DiGraph(
        [(d[i], d[-i], i) for i in d.keys() if i > 0],
        format="list_of_edges",
        loops=True,
        multiedges=True,
    )
    return dom.canonical_label() if canonical else dom.relabel() or dom


def train_track_domains(
    f: PartialGraphMap, rank: int, germs: DisjointSet | None = None
):
    if not f.is_complete():
        raise ValueError(
            f"Map {f} is missing images for {f.missing_images()}. A complete map is expected."
        )

    if germs is None:
        germs = f.domain_partition()

    for partitions in train_track_partitions(germs, rank).values():
        for part in partitions:
            yield domain_graph(part)


def train_track_maps(tg: DiGraph, rank: int):
    if not tg.is_strongly_connected():
        raise ValueError("Transition digraph must be strongly connected.")

    candidate_maps = candiate_train_track_maps(tg, rank)

    for f, germs in candidate_maps:
        doms = [*train_track_domains(f, rank, germs)]
        if doms:
            yield (f, doms)
